# This file was auto-generated by Fern from our API Definition.

import enum


class NeuralAudioEnvironment(enum.Enum):
    PRODUCTION = "https://api.neuralaudio.solutions"
    PRODUCTION_US = "https://api.us.neuralaudio.solutions"
